//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;
using Crud.Domain;
using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;
using System.Data.SqlClient;
using LinqToDB.Data;

namespace DataModel
{
	/// <summary>
	/// Database       : DadosCliente
	/// Data Source    : INVENT052\SQLINVENT52
	/// Server Version : 15.00.2000
	/// </summary>
	public partial class DadosClienteDB : LinqToDB.Data.DataConnection
	{
		public ITable<DadosCliente> dadosClientes { get { return this.GetTable<DadosCliente>(); } }

		public DadosClienteDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DadosClienteDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DadosClienteDB(LinqToDbConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DadosClienteDB(LinqToDbConnectionOptions<DadosClienteDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	public static partial class TableExtensions
	{
		public static DadosCliente Find(this ITable<DadosCliente> table, string CPF)
		{
			return table.FirstOrDefault(t =>
				t.CPF == CPF);
		}
	}
}

#pragma warning restore 1591
